set_project("mw120rproxy-startup-tests")
set_allowedplats("windows")
set_allowedarchs("x64")
set_languages("cxx20", "c17")

target("xsurface_tests")
    set_kind("binary")
    set_runtimes("MT")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN")
    add_syslinks("d3dcompiler")
    add_ldflags("/BASE:0x180000000", "/DYNAMICBASE:NO", {force = true})
    set_targetdir("../../test-out")
    add_files("xsurface_tests.cpp", "../../iw8-zonetool/src/zonetool/convert/xsurface.cpp")
    add_includedirs("../../iw8-zonetool/src", "../../iw8-zonetool/src/zonetool")
    add_files("../../iw8-zonetool/src/zonetool/convert/conv_xsurface.cpp")
    add_files("../../iw8-zonetool/src/zonetool/convert/conv_xmodel.cpp")
    add_files("../../iw8-zonetool/src/zonetool/dumpsrc/read_xmodel.cpp")
    add_files("../../iw8-zonetool/src/zonetool/iw8/write_xmodel.cpp")
    add_files("../../iw8-zonetool/src/zonetool/iw8/write_xsurface.cpp",
              "../../iw8-zonetool/src/zonetool/iw8/replay_render.cpp",
              "../../iw8-zonetool/src/zonetool/iw8/iw8_zone.cpp",
              "../../iw8-zonetool/src/zonetool/dumpsrc/read_xsurface.cpp")
    add_files("../../iw8-zonetool/src/common/fs_util.cpp", "../../iw8-zonetool/src/common/ff_io.cpp")

target("replay_binding_tests")
    set_kind("binary")
    set_runtimes("MT")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN")
    add_syslinks("d3dcompiler")
    set_targetdir("../../test-out")
    add_includedirs("../../iw8-zonetool/src", "../../iw8-zonetool/src/zonetool")
    add_files("replay_binding_tests.cpp", "../../iw8-zonetool/src/zonetool/iw8/replay_render.cpp",
              "../../iw8-zonetool/src/zonetool/iw8/iw8_zone.cpp")
target("collision_ray_tests")
    set_kind("binary")
    set_runtimes("MT")
    set_optimize("fastest")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN")
    set_targetdir("../../test-out")
    add_files("collision_ray_tests.cpp")
target("ambient_gpu_tests")
    set_kind("binary")
    set_runtimes("MT")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN")
    add_syslinks("kernel32", "d3d12", "dxgi", "d3dcompiler")
    set_targetdir("../../test-out")
    add_files("ambient_gpu_tests.cpp")
target("ambient_grid_tests")
    set_kind("binary")
    set_runtimes("MT")
    set_optimize("fastest")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN")
    set_targetdir("../../test-out")
    add_files("ambient_grid_tests.cpp")
target("engine_tests")
    set_kind("binary")
    set_runtimes("MT")
    set_optimize("fastest")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN", "_CRT_SECURE_NO_WARNINGS")
    add_includedirs("..", "../sdk_shim")
    add_syslinks("kernel32", "user32")
    set_targetdir("../../test-out")
    add_files("engine_tests.cpp", "../engine_diagnostics.cpp", "../inline_hook.cpp", "../log.cpp")
    add_files("../thirdparty/minhook/src/*.c", "../thirdparty/minhook/src/hde/hde64.c")

target("custom_map_tests")
    set_kind("binary")
    set_runtimes("MT")
    set_optimize("fastest")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN", "_CRT_SECURE_NO_WARNINGS")
    add_includedirs("..", "../sdk_shim")
    add_syslinks("kernel32", "user32")
    set_targetdir("../../test-out")
    add_files("custom_map_tests.cpp", "../command_text.cpp", "../custom_maps.cpp", "../custom_map_loader.cpp", "../custom_physics.cpp", "../custom_collision.cpp", "../custom_images.cpp", "../custom_audio.cpp", "../custom_surfaces.cpp", "../custom_omnvars.cpp",
              "../developer_ui.cpp", "../noclip.cpp", "../custom_map_ui.cpp", "../custom_ladders.cpp", "../custom_glass.cpp", "../custom_doors.cpp", "../inline_hook.cpp", "../log.cpp")
    add_files("../thirdparty/minhook/src/*.c", "../thirdparty/minhook/src/hde/hde64.c")

target("fastfile_tests")
    set_kind("binary")
    set_runtimes("MT")
    set_optimize("fastest")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN", "_CRT_SECURE_NO_WARNINGS")
    add_includedirs("..", "../sdk_shim")
    add_syslinks("kernel32", "user32")
    set_targetdir("../../test-out")
    add_files("fastfile_tests.cpp", "../fastfile_diagnostics.cpp", "../inline_hook.cpp", "../log.cpp")
    add_files("../thirdparty/minhook/src/*.c", "../thirdparty/minhook/src/hde/hde64.c")

target("startup_tests")
    set_kind("binary")
    set_runtimes("MT")
    set_optimize("fastest")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN", "_CRT_SECURE_NO_WARNINGS")
    add_includedirs("..", "../sdk_shim")
    add_syslinks("kernel32", "user32", "gdi32")
    set_targetdir("../../test-out")
    add_files("resources.rc")
    add_files("startup_tests.cpp", "../inline_hook.cpp", "../dvar_patches.cpp", "../log.cpp", "../trigger.cpp", "../diagnostics.cpp", "../startup_compat.cpp")
    add_files("../thirdparty/minhook/src/*.c", "../thirdparty/minhook/src/hde/hde64.c")

target("auth_tests")
    set_kind("binary")
    set_runtimes("MT")
    set_optimize("fastest")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN", "_CRT_SECURE_NO_WARNINGS")
    add_includedirs("..", "../sdk_shim")
    add_syslinks("kernel32", "user32", "bcrypt")
    set_targetdir("../../test-out")
    add_files("auth_tests.cpp", "../offline_auth.cpp", "../inline_hook.cpp", "../log.cpp")
    add_files("../thirdparty/minhook/src/*.c", "../thirdparty/minhook/src/hde/hde64.c")

target("render_raster_tests")
    set_kind("binary")
    set_runtimes("MT")
    set_optimize("fastest")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN", "_CRT_SECURE_NO_WARNINGS")
    add_syslinks("kernel32", "d3d11", "d3dcompiler")
    set_targetdir("../../test-out")
    add_files("render_raster_tests.cpp")

target("world_vertex_tests")
    set_kind("binary")
    set_runtimes("MT")
    set_optimize("fastest")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN")
    add_syslinks("kernel32", "d3d11", "d3dcompiler")
    set_targetdir("../../test-out")
    add_files("world_vertex_tests.cpp")

target("native_grid_gpu_tests")
    set_kind("binary")
    set_runtimes("MT")
    set_optimize("fastest")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN")
    add_syslinks("kernel32", "d3d12", "dxgi", "d3dcompiler")
    set_targetdir("../../test-out")
    add_files("native_grid_gpu_tests.cpp")

target("model_vertex_tests")
    set_kind("binary")
    set_runtimes("MT")
    set_optimize("fastest")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN")
    add_syslinks("kernel32", "d3d11", "d3dcompiler")
    set_targetdir("../../test-out")
    add_files("model_vertex_tests.cpp")


target("door_tests")
    set_kind("binary")
    set_runtimes("MT")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN", "_CRT_SECURE_NO_WARNINGS")
    add_includedirs("..", "../sdk_shim")
    add_syslinks("kernel32", "user32")
    set_targetdir("../../test-out")
    add_files("door_tests.cpp", "../custom_doors.cpp", "../log.cpp")

target("door_ui_tests")
    set_kind("binary")
    set_runtimes("MT")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN", "_CRT_SECURE_NO_WARNINGS")
    add_includedirs("..", "../sdk_shim")
    add_syslinks("kernel32", "user32")
    set_targetdir("../../test-out")
    add_files("door_ui_tests.cpp", "../custom_door_ui.cpp", "../inline_hook.cpp", "../log.cpp")
    add_files("../thirdparty/minhook/src/*.c", "../thirdparty/minhook/src/hde/hde64.c")
