// iw3_assets_stub.cpp — no-op STUB definitions of the Stage-A IW3 dumpers (convert/registry.h).
// Each logs "TODO <fam>". Later per-asset agents REPLACE these by adding their own .cpp that defines
// the same symbol (and removing/emptying this stub for that family) — they do NOT edit this file's
// owner's other modules.
#include "../convert/registry.h"
#include "../common/log.h"
#include "iw3_zone.h"
#include "../zonesrc/zone_source.h"

namespace convert {

// All five families (image, material, xmodel, xsurface, maps) are now IMPLEMENTED in their own
// iw3/iw3_asset_<fam>.cpp translation units. No stubs remain — this file is intentionally empty.

} // namespace convert
