"""Compile the owned graybox pixel shader and prepare its Replay technique data.

Uses the local Replay shader templates generated by setup_shader_templates.py.
"""

import ctypes as C
import hashlib
import json
from pathlib import Path
import struct
import argparse
import re

root = Path(__file__).resolve().parents[2] / "custom_map_sources/mp_test"
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--source", type=Path, default=root / "shaders/graybox.hlsl")
parser.add_argument("--target-root", type=Path, default=root)
parser.add_argument("--map", default="mp_test")
args = parser.parse_args()
if not re.fullmatch(r"mp_[a-z0-9_]{1,60}", args.map):
    raise ValueError("Invalid map id")
source = args.source.read_bytes()
d = C.WinDLL("d3dcompiler_47")
fn = d.D3DCompile
fn.argtypes = [
    C.c_void_p,
    C.c_size_t,
    C.c_char_p,
    C.c_void_p,
    C.c_void_p,
    C.c_char_p,
    C.c_char_p,
    C.c_uint,
    C.c_uint,
    C.POINTER(C.c_void_p),
    C.POINTER(C.c_void_p),
]
fn.restype = C.c_long


def blob(ptr):
    if not ptr:
        return b""
    vt = C.cast(ptr, C.POINTER(C.POINTER(C.c_void_p))).contents
    p = C.WINFUNCTYPE(C.c_void_p, C.c_void_p)(vt[3])(ptr)
    size = C.WINFUNCTYPE(C.c_size_t, C.c_void_p)(vt[4])(ptr)
    value = C.string_at(p, size)
    C.WINFUNCTYPE(C.c_ulong, C.c_void_p)(vt[2])(ptr)
    return value


out = C.c_void_p()
error = C.c_void_p()
buf = C.create_string_buffer(source)
hr = fn(
    buf,
    len(source),
    args.source.name.encode(),
    None,
    None,
    b"main",
    b"ps_5_0",
    1 << 15,
    0,
    C.byref(out),
    C.byref(error),
)
message = blob(error).decode(errors="replace")
if hr < 0:
    raise RuntimeError(message)
code = blob(out)
if not code.startswith(b"DXBC"):
    raise ValueError("Compiler did not emit DXBC")
digest = hashlib.sha256(code).digest()
shader_name = "mw120r_graybox_" + digest.hex()[:24]
j = json.loads((root / "shaders/replay_static_world_techset.json").read_text())
j["name"] = (
    "tw/mw120r_graybox_v1"
    if args.map == "mp_test"
    else "tw/mw120r_" + args.map + "_" + digest.hex()[:12]
)
lit = j["techniques"][-1]
old = lit["shaders"][3]
shader = j["shaders"].pop("17:" + old)
shader["name"] = shader_name
shader["debugName"] = args.source.name
shader["program"] = code.hex()
header = bytearray(40)
struct.pack_into("<II", header, 32, len(code), int.from_bytes(digest[:4], "little"))
shader["header"] = header.hex()
j["shaders"]["17:" + shader_name] = shader
lit["shaders"][3] = shader_name
lit["name"] = "TECHNIQUE_LIT_FORWARDPLUS_BITMASK_" + j["name"].removeprefix("tw/")
# The serialized pipeline hash is a cache identity, not a live handle. Use a
# different identity for the owned shader so a stock PSO cannot be reused.
states = bytearray.fromhex(lit["states"])
for offset in range(0, len(states), 16):
    states[offset : offset + 8] = hashlib.sha256(
        code + lit["header"].encode() + bytes([offset])
    ).digest()[:8]
lit["states"] = states.hex()
target = args.target_root / f"dump/maps/mp/{args.map}.d3dbsp.techset.json"
target.write_text(json.dumps(j, indent=2) + "\n")
material = target.with_name(args.map + ".d3dbsp.material.json")
m = json.loads(material.read_text())
m["techset"] = j["name"]
material.write_text(json.dumps(m, indent=2) + "\n")
print(
    json.dumps(
        {
            "shader": shader_name,
            "bytes": len(code),
            "sha256": digest.hex(),
            "source_sha256": hashlib.sha256(source).hexdigest(),
        },
        indent=2,
    )
)
