// Generated by tools/compile_test_brushes.py from the supplied CoD4 mp_test.map.
#pragma once
namespace testbrushes {
struct Brush { float mins[3], maxs[3]; bool sky; };
inline constexpr Brush brushes[] = {
    {{-832.0f,816.0f,0.0f},{832.0f,832.0f,128.0f},false},
    {{-832.0f,-832.0f,0.0f},{832.0f,-816.0f,128.0f},false},
    {{816.0f,-832.0f,0.0f},{832.0f,832.0f,128.0f},false},
    {{-832.0f,-832.0f,0.0f},{-816.0f,832.0f,128.0f},false},
    {{-832.0f,-832.0f,-16.0f},{832.0f,832.0f,0.0f},false},
    {{-896.0f,-896.0f,-64.0f},{896.0f,896.0f,-48.0f},true},
    {{-896.0f,-896.0f,496.0f},{896.0f,896.0f,512.0f},true},
    {{-896.0f,-896.0f,-64.0f},{896.0f,-880.0f,512.0f},true},
    {{880.0f,-896.0f,-64.0f},{896.0f,896.0f,512.0f},true},
    {{-896.0f,880.0f,-64.0f},{896.0f,896.0f,512.0f},true},
    {{-896.0f,-896.0f,-64.0f},{-880.0f,896.0f,512.0f},true},
};
}
